- hosts: all
  become: true
  tasks:
    - name: Delete old deployment
      ansible.builtin.command:
        cmd: kubectl delete -f /home/ubuntu/Deployment.yml
      ignore_errors: true
    - name: Delete old service
      ansible.builtin.command:
        cmd: kubectl delete -f /home/ubuntu/Service.yml
      ignore_errors: true
    - name: Create new deployment
      ansible.builtin.command:
        cmd: kubectl apply -f /home/ubuntu/Deployment.yml
    - name: Create new service
      ansible.builtin.command:
        cmd: kubectl apply -f /home/ubuntu/Service.yml
