apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgaurav8026
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kgaurav8026
  template:
    metadata:
      labels:
        app: kgaurav8026
    spec:
      containers:
        - name: kgaurav8026
          image: kgaurav8026/pipeline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
