kind: Deployment
apiVersion: apps/v1
metadata:
  name: kgaurav8026
spec:
  replicas: 2
  selector: # tells the controller which pods to watch/belong to
    matchLabels:
      app: kgaurav8026
  template:
    metadata:
      labels:
        app: kgaurav8026
    spec:
      containers:
        - name: kgaurav8026
          image: kgaurav8026/pipeline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
